version: 0.2

env:
  shell: bash
#  secrets-manager:

phases:
  install:
    commands:
      - echo $PATH
      - cat ~/.bashrc
      - source ~/.bashrc
      - echo $PATH
      - echo $SHELL
      - whoami
      - pwd
      - composer update
      - composer install
      - /root/.nvm/versions/node/v21.2.0/bin/npm use 21.2
      - npm i
  build:
    commands:
      - php artisan key:generate
      - php artisan config:cache
      - npm run build

  post_build:
    commands:
      - echo "Post Build"

artifacts:
  files: '**/*'
