version: 0.2

#env:
#  secrets-manager:

phases:
  install:
    commands:
      - find ./
      - whoami
      - pwd
      - composer update
      - composer install
      - /root/.nvm/versions/node/v21.2.0/bin/npm i
  build:
    commands:
      - php artisan key:generate
      - php artisan config:cache
      - /root/.nvm/versions/node/v21.2.0/bin/npm run build

  post_build:
    commands:
      - echo "Post Build"

artifacts:
  files: '**/*'
