# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["21.6.1"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    # - name: Install packages
    #   run: sudo apt-get update; apt-get install composer nginx redis php-fpm php-xml php-curl php-zip php-intl php-mbstring php-pgsql php-pear php-dev libhiredis-dev -y

    # - name: Install phpredis vi pecl
    #   run: sudo pecl install redis
      
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
