# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["21.6.1"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    - name: Update packages
      run: sudo apt-get update;
      
    - name: Install packages
      run: sudo apt-get install composer nginx redis php-fpm php-xml php-curl php-zip php-intl php-mbstring php-pgsql php-pear php-dev libhiredis-dev -y

    - name: Set PHP version as environment variable
      id: php_version
      run: echo "PHP_VERSION=$(php -v | head -n 1 | cut -d' ' -f2| cut -d '-' -df1)" >> $GITHUB_ENV ; PHP_MAJOR_VERSION=$(echo "$PHP_VERSION" | cut -d '.' -f 1,2)

    - name: Display PHP version
      run: echo "PHP version is $PHP_VERSION", and major version is $PHP_MAJOR_VERSION

    - name: Install php extension
      run: echo "extension=redis.so" | sudo tee -a /etc/php/$PHP_MAJOR_VERSION/cli/conf.d/20-redis.ini

    - name: Install phpredis vi pecl
      run: sudo pecl install redis -y 

    - name: Run composer
      run: composer update; composer i
      
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
